"""Third Migration

Revision ID: c7489a7353c4
Revises: 1cffc0f47eeb
Create Date: 2020-06-14 14:04:12.398373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7489a7353c4'
down_revision = '1cffc0f47eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maillist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maillist')
    # ### end Alembic commands ###
